apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: mysql-container
          image: datascientest/mysql-k8s:1.0.0
          ports:
            - containerPort: 3306
        - name: fastapi-container
          image: fastapi:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-eval-secret
                key: mysql-root-password
